Data Collection - Matthew Jarrams

Notebook used to read JSON file (business and reviews) and extract Edmonton Resturants.

Goal was to create a CSV of Edmonton reviews with the columns containing information I needed for analysis.

In [3]:
import json
import pandas as pd
import os

Read JSON file of businesses and explore some of the cities

In [4]:
test = pd.DataFrame()

test = pd.read_json('yelp_academic_dataset_business.json',lines=True)

In [6]:
cities = test.groupby(by=['state', 'city']).count()

In [7]:
states = test.groupby(by=['state']).count()

In [8]:
states

,business_id,name,address,city,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
state,,,,,,,,,,,,,
AB,5573,5573,5573,5573,5573,5573,5573,5573,5573,5573,4967,5572,4546
AZ,9912,9912,9912,9912,9912,9912,9912,9912,9912,9912,8920,9906,8496
CA,5203,5203,5203,5203,5203,5203,5203,5203,5203,5203,4669,5202,4303
CO,3,3,3,3,3,3,3,3,3,3,3,3,1
DE,2265,2265,2265,2265,2265,2265,2265,2265,2265,2265,2068,2262,1881
FL,26330,26330,26330,26330,26330,26330,26330,26330,26330,26330,23735,26309,22877
HI,2,2,2,2,2,2,2,2,2,2,2,2,1
ID,4467,4467,4467,4467,4467,4467,4467,4467,4467,4467,4067,4464,3892
IL,2145,2145,2145,2145,2145,2145,2145,2145,2145,2145,1970,2144,1795
IN,11247,11247,11247,11247,11247,11247,11247,11247,11247,11247,10311,11243,9513
LA,9924,9924,9924,9924,9924,9924,9924,9924,9924,9924,9123,9916,8150
MA,2,2,2,2,2,2,2,2,2,2,1,2,0
MI,1,1,1,1,1,1,1,1,1,1,1,1,1
MO,10913,10913,10913,10913,10913,10913,10913,10913,10913,10913,10047,10907,9450
MT,1,1,1,1,1,1,1,1,1,1,1,1,1
NC,1,1,1,1,1,1,1,1,1,1,1,1,1
NJ,8536,8536,8536,8536,8536,8536,8536,8536,8536,8536,7771,8527,7131
NV,7715,7715,7715,7715,7715,7715,7715,7715,7715,7715,6859,7706,6454
PA,34039,34039,34039,34039,34039,34039,34039,34039,34039,34039,31081,34013,28224
SD,1,1,1,1,1,1,1,1,1,1,1,1,1
TN,12056,12056,12056,12056,12056,12056,12056,12056,12056,12056,10996,12051,10398
TX,4,4,4,4,4,4,4,4,4,4,2,4,4
UT,1,1,1,1,1,1,1,1,1,1,1,1,0
VI,1,1,1,1,1,1,1,1,1,1,1,1,1
VT,1,1,1,1,1,1,1,1,1,1,1,1,1
WA,2,2,2,2,2,2,2,2,2,2,2,2,1
XMS,1,1,1,1,1,1,1,1,1,1,1,1,0

In [9]:
cities

                               business_id  name  address  postal_code  \
state city
AB    AB Edmonton                        1     1        1            1
      Alberta Park Industrial            1     1        1            1
      Beaumont                          10    10       10           10
      Downtown                           1     1        1            1
      East Edmonton                      1     1        1            1
...                                    ...   ...      ...          ...
VI    Tortola                            1     1        1            1
VT    Bennington                         1     1        1            1
WA    College Place                      1     1        1            1
      Spokane                            1     1        1            1
XMS   Liverpool                          1     1        1            1

                               latitude  longitude  stars  review_count  \
state city
AB    AB Edmonton                     1          1      1             1
      Alberta Park Industrial         1          1      1             1
      Beaumont                       10         10     10            10
      Downtown                        1          1      1             1
      East Edmonton                   1          1      1             1
...                                 ...        ...    ...           ...
VI    Tortola                         1          1      1             1
VT    Bennington                      1          1      1             1
WA    College Place                   1          1      1             1
      Spokane                         1          1      1             1
XMS   Liverpool                       1          1      1             1

                               is_open  attributes  categories  hours
state city
AB    AB Edmonton                    1           1           1      1
      Alberta Park Industrial        1           0           1      0
      Beaumont                      10          10          10      7
      Downtown                       1           1           1      0
      East Edmonton                  1           1           1      1
...                                ...         ...         ...    ...
VI    Tortola                        1           1           1      1
VT    Bennington                     1           1           1      1
WA    College Place                  1           1           1      1
      Spokane                        1           1           1      0
XMS   Liverpool                      1           1           1      0

[1467 rows x 12 columns]

In [10]:
cities = cities[cities['business_id'] > 300]

In [11]:
cities

                        business_id   name  address  postal_code  latitude  \
state city
AB    Edmonton                 5054   5054     5054         5054      5054
AZ    Tucson                   9249   9249     9249         9249      9249
CA    Goleta                    798    798      798          798       798
      Santa Barbara            3829   3829     3829         3829      3829
DE    Newark                    359    359      359          359       359
      Wilmington               1445   1445     1445         1445      1445
FL    Brandon                  1033   1033     1033         1033      1033
      Clearwater               2221   2221     2221         2221      2221
      Dunedin                   490    490      490          490       490
      Largo                    1002   1002     1002         1002      1002
      Lutz                      591    591      591          591       591
      New Port Richey           604    604      604          604       604
      Palm Harbor               665    665      665          665       665
      Pinellas Park             512    512      512          512       512
      Riverview                 588    588      588          588       588
      Saint Petersburg         1663   1663     1663         1663      1663
      Seminole                  359    359      359          359       359
      Spring Hill               400    400      400          400       400
      St Petersburg             387    387      387          387       387
      St. Petersburg           1185   1185     1185         1185      1185
      Tampa                    9048   9048     9048         9048      9048
      Tarpon Springs            398    398      398          398       398
      Wesley Chapel             560    560      560          560       560
ID    Boise                    2937   2937     2937         2937      2937
      Meridian                 1042   1042     1042         1042      1042
IN    Carmel                    967    967      967          967       967
      Fishers                   570    570      570          570       570
      Greenwood                 649    649      649          649       649
      Indianapolis             7540   7540     7540         7540      7540
LA    Kenner                    584    584      584          584       584
      Metairie                 1643   1643     1643         1643      1643
      New Orleans              6208   6208     6208         6208      6208
MO    Saint Louis              4827   4827     4827         4827      4827
      St Louis                  356    356      356          356       356
      St. Louis                1254   1254     1254         1254      1254
NJ    Cherry Hill               959    959      959          959       959
      Marlton                   415    415      415          415       415
NV    Reno                     5932   5932     5932         5932      5932
      Sparks                   1623   1623     1623         1623      1623
PA    Ardmore                   376    376      376          376       376
      Bensalem                  454    454      454          454       454
      Doylestown                539    539      539          539       539
      Exton                     419    419      419          419       419
      King of Prussia           560    560      560          560       560
      Lansdale                  378    378      378          378       378
      Media                     371    371      371          371       371
      Norristown                448    448      448          448       448
      Philadelphia            14567  14567    14567        14567     14567
      Phoenixville              365    365      365          365       365
      Wayne                     375    375      375          375       375
      West Chester              838    838      838          838       838
TN    Brentwood                 644    644      644          644       644
      Franklin                 1410   1410     1410         1410      1410
      Hendersonville            484    484      484          484       484
      Nashville                6968   6968     6968         6968      6968
      Smyrna                    365    365      365          365       365

                        longitude  stars  review_count  is_open  attributes  \
state city
AB    Edmonton               5054   5054          5054     5054        4506
AZ    Tucson                 9249   9249          9249     9249        8327
CA    Goleta                  798    798           798      798         720
      Santa Barbara          3829   3829          3829     3829        3430
DE    Newark                  359    359           359      359         330
      Wilmington             1445   1445          1445     1445        1314
FL    Brandon                1033   1033          1033     1033         941
      Clearwater             2221   2221          2221     2221        1989
      Dunedin                 490    490           490      490         456
      Largo                  1002   1002          1002     1002         905
      Lutz                    591    591           591      591         517
      New Port Richey         604    604           604      604         532
      Palm Harbor             665    665           665      665         601
      Pinellas Park           512    512           512      512         463
      Riverview               588    588           588      588         531
      Saint Petersburg       1663   1663          1663     1663        1495
      Seminole                359    359           359      359         329
      Spring Hill             400    400           400      400         361
      St Petersburg           387    387           387      387         347
      St. Petersburg         1185   1185          1185     1185        1074
      Tampa                  9048   9048          9048     9048        8169
      Tarpon Springs          398    398           398      398         359
      Wesley Chapel           560    560           560      560         513
ID    Boise                  2937   2937          2937     2937        2673
      Meridian               1042   1042          1042     1042         938
IN    Carmel                  967    967           967      967         878
      Fishers                 570    570           570      570         526
      Greenwood               649    649           649      649         593
      Indianapolis           7540   7540          7540     7540        6917
LA    Kenner                  584    584           584      584         520
      Metairie               1643   1643          1643     1643        1530
      New Orleans            6208   6208          6208     6208        5713
MO    Saint Louis            4827   4827          4827     4827        4403
      St Louis                356    356           356      356         326
      St. Louis              1254   1254          1254     1254        1149
NJ    Cherry Hill             959    959           959      959         866
      Marlton                 415    415           415      415         379
NV    Reno                   5932   5932          5932     5932        5271
      Sparks                 1623   1623          1623     1623        1452
PA    Ardmore                 376    376           376      376         342
      Bensalem                454    454           454      454         415
      Doylestown              539    539           539      539         491
      Exton                   419    419           419      419         384
      King of Prussia         560    560           560      560         506
      Lansdale                378    378           378      378         346
      Media                   371    371           371      371         336
      Norristown              448    448           448      448         401
      Philadelphia          14567  14567         14567    14567       13397
      Phoenixville            365    365           365      365         335
      Wayne                   375    375           375      375         340
      West Chester            838    838           838      838         765
TN    Brentwood               644    644           644      644         587
      Franklin               1410   1410          1410     1410        1279
      Hendersonville          484    484           484      484         435
      Nashville              6968   6968          6968     6968        6377
      Smyrna                  365    365           365      365         333

                        categories  hours
state city
AB    Edmonton                5053   4104
AZ    Tucson                  9243   7915
CA    Goleta                   798    662
      Santa Barbara           3828   3171
DE    Newark                   358    304
      Wilmington              1443   1187
FL    Brandon                 1032    901
      Clearwater              2221   1912
      Dunedin                  490    412
      Largo                   1000    890
      Lutz                     591    532
      New Port Richey          603    518
      Palm Harbor              665    589
      Pinellas Park            512    456
      Riverview                588    531
      Saint Petersburg        1660   1391
      Seminole                 358    322
      Spring Hill              400    356
      St Petersburg            387    371
      St. Petersburg          1185   1019
      Tampa                   9040   7905
      Tarpon Springs           397    334
      Wesley Chapel            559    483
ID    Boise                   2934   2525
      Meridian                1042    931
IN    Carmel                   966    849
      Fishers                  570    501
      Greenwood                649    549
      Indianapolis            7537   6294
LA    Kenner                   583    463
      Metairie                1639   1408
      New Orleans             6207   5050
MO    Saint Louis             4824   3938
      St Louis                 356    337
      St. Louis               1254   1189
NJ    Cherry Hill              959    808
      Marlton                  414    358
NV    Reno                    5926   4946
      Sparks                  1620   1386
PA    Ardmore                  376    315
      Bensalem                 453    377
      Doylestown               538    476
      Exton                    419    367
      King of Prussia          559    461
      Lansdale                 378    323
      Media                    370    301
      Norristown               447    358
      Philadelphia           14558  11784
      Phoenixville             365    313
      Wayne                    375    313
      West Chester             838    726
TN    Brentwood                644    580
      Franklin                1410   1240
      Hendersonville           483    422
      Nashville               6966   5933
      Smyrna                   365    315

In [13]:
test.head()
test.is_open.value_counts()

1    119698
0     30648
Name: is_open, dtype: int64

In [14]:
test['categories'][0:10]

0    Doctors, Traditional Chinese Medicine, Naturop...
1    Shipping Centers, Local Services, Notaries, Ma...
2    Department Stores, Shopping, Fashion, Home & G...
3    Restaurants, Food, Bubble Tea, Coffee & Tea, B...
4                            Brewpubs, Breweries, Food
5    Burgers, Fast Food, Sandwiches, Food, Ice Crea...
6    Sporting Goods, Fashion, Shoe Stores, Shopping...
7                  Synagogues, Religious Organizations
8    Pubs, Restaurants, Italian, Bars, American (Tr...
9    Ice Cream & Frozen Yogurt, Fast Food, Burgers,...
Name: categories, dtype: object

Split the categories into individual words to find the resturants

In [15]:
df_explode = test.assign(categories = test.categories.str.split(', ')).explode('categories')
df_explode.sample(3)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
142248,e2RBDxidD3rNQuGvJLHmpw,Sultan's Grill & Ginger Juice Bar,1602 21st Ave S,Nashville,TN,37212,36.138607,-86.800360,2.5,53,1,"{'RestaurantsDelivery': 'True', 'Caters': 'Tru...",Bars,"{'Monday': '10:0-23:0', 'Tuesday': '10:0-23:0'..."
44553,eFCaCZBcUxA9o04QJ939-A,Provence Catering,2068 W Main St,Jeffersonville,PA,19403,40.134323,-75.380423,5.0,5,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...",Event Planning & Services,"{'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ..."
71192,mqvpxirGRGp761VG6rLV5Q,TLC Laser Eye Centers,"600 W Germantown Pike Cri Bld, Ste 160",Plymouth Meeting,PA,19462,40.118433,-75.284970,4.0,5,0,None,Optometrists,"{'Monday': '9:0-17:0', 'Tuesday': '9:0-17:0', ..."

In [16]:
df_explode.count()

business_id     668695
name            668695
address         668695
city            668695
state           668695
postal_code     668695
latitude        668695
longitude       668695
stars           668695
review_count    668695
is_open         668695
attributes      622088
categories      668592
hours           594901
dtype: int64

In [17]:
print('Total number of categories:', len(df_explode.categories.value_counts()))
print('Top 10 categories:')
df_explode.categories.value_counts()[30:60]

Total number of categories: 1311
Top 10 categories:

Doctors                      3763
Pets                         3758
Real Estate                  3577
Seafood                      3539
Fitness & Instruction        3293
Professional Services        3270
Hair Removal                 3239
Desserts                     3186
Chinese                      3169
Bakeries                     3150
Grocery                      3139
Salad                        3064
Hotels                       2977
Chicken Wings                2966
Cafes                        2756
Ice Cream & Frozen Yogurt    2657
Caterers                     2645
Pet Services                 2626
Dentists                     2528
Skin Care                    2498
Venues & Event Spaces        2480
Tires                        2471
Wine & Spirits               2413
Beer                         2413
Delis                        2393
Oil Change Stations          2356
Waxing                       2333
Contractors                  2327
Women's Clothing             2184
Massage                      2134
Name: categories, dtype: int64

In [18]:
food = test[test['categories'].str.contains(
                         'Restaurants', case=False, na=False)]
print(food.shape)
food.head()

(52268, 14)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,Ashland City,TN,37015,36.269593,-87.058943,2.0,6,1,"{'BusinessParking': 'None', 'BusinessAcceptsCr...","Burgers, Fast Food, Sandwiches, Food, Ice Crea...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-22:0', '..."
8,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,8025 Mackenzie Rd,Affton,MO,63123,38.565165,-90.321087,3.0,19,0,"{'Caters': 'True', 'Alcohol': 'u'full_bar'', '...","Pubs, Restaurants, Italian, Bars, American (Tr...",None
9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,2312 Dickerson Pike,Nashville,TN,37207,36.208102,-86.768170,1.5,10,1,"{'RestaurantsAttire': ''casual'', 'Restaurants...","Ice Cream & Frozen Yogurt, Fast Food, Burgers,...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-21:0', '..."
11,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,,Tampa Bay,FL,33602,27.955269,-82.456320,4.0,10,1,"{'Alcohol': ''none'', 'OutdoorSeating': 'None'...","Vietnamese, Food, Restaurants, Food Trucks","{'Monday': '11:0-14:0', 'Tuesday': '11:0-14:0'..."

In [19]:
food_explode = food.assign(categories = food.categories.str.split(', ')).explode('categories')
food_explode

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...",Restaurants,"{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...",Food,"{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...",Bubble Tea,"{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...",Coffee & Tea,"{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...",Bakeries,"{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150339,2O2K6SXPWv56amqxCECd4w,The Plum Pit,4405 Pennell Rd,Aston,DE,19014,39.856185,-75.427725,4.5,14,1,"{'RestaurantsDelivery': 'False', 'BusinessAcce...",Food Trucks,"{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
150339,2O2K6SXPWv56amqxCECd4w,The Plum Pit,4405 Pennell Rd,Aston,DE,19014,39.856185,-75.427725,4.5,14,1,"{'RestaurantsDelivery': 'False', 'BusinessAcce...",Caterers,"{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
150339,2O2K6SXPWv56amqxCECd4w,The Plum Pit,4405 Pennell Rd,Aston,DE,19014,39.856185,-75.427725,4.5,14,1,"{'RestaurantsDelivery': 'False', 'BusinessAcce...",Event Planning & Services,"{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
150340,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,2470 Guardian Road NW,Edmonton,AB,T5T 1K8,53.509649,-113.675999,4.5,18,0,"{'Ambience': '{'touristy': False, 'hipster': F...",Middle Eastern,"{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
150340,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,2470 Guardian Road NW,Edmonton,AB,T5T 1K8,53.509649,-113.675999,4.5,18,0,"{'Ambience': '{'touristy': False, 'hipster': F...",Restaurants,"{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."

In [20]:
food_explode[food_explode['categories'].notna()]

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...",Restaurants,"{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...",Food,"{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...",Bubble Tea,"{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...",Coffee & Tea,"{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...",Bakeries,"{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150339,2O2K6SXPWv56amqxCECd4w,The Plum Pit,4405 Pennell Rd,Aston,DE,19014,39.856185,-75.427725,4.5,14,1,"{'RestaurantsDelivery': 'False', 'BusinessAcce...",Food Trucks,"{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
150339,2O2K6SXPWv56amqxCECd4w,The Plum Pit,4405 Pennell Rd,Aston,DE,19014,39.856185,-75.427725,4.5,14,1,"{'RestaurantsDelivery': 'False', 'BusinessAcce...",Caterers,"{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
150339,2O2K6SXPWv56amqxCECd4w,The Plum Pit,4405 Pennell Rd,Aston,DE,19014,39.856185,-75.427725,4.5,14,1,"{'RestaurantsDelivery': 'False', 'BusinessAcce...",Event Planning & Services,"{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
150340,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,2470 Guardian Road NW,Edmonton,AB,T5T 1K8,53.509649,-113.675999,4.5,18,0,"{'Ambience': '{'touristy': False, 'hipster': F...",Middle Eastern,"{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
150340,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,2470 Guardian Road NW,Edmonton,AB,T5T 1K8,53.509649,-113.675999,4.5,18,0,"{'Ambience': '{'touristy': False, 'hipster': F...",Restaurants,"{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."

In [21]:
print('Total number of categories:', len(food_explode.categories.value_counts()))
print('Top 10 categories:')
food_explode.categories.value_counts()[:30]

Total number of categories: 728
Top 10 categories:

Restaurants                  52268
Food                         15472
Nightlife                     8723
Sandwiches                    8366
Bars                          8337
American (Traditional)        8139
Pizza                         7093
Fast Food                     6472
Breakfast & Brunch            6239
American (New)                6097
Burgers                       5636
Mexican                       4600
Italian                       4573
Coffee & Tea                  4053
Seafood                       3539
Chinese                       3169
Event Planning & Services     3068
Salad                         3064
Chicken Wings                 2966
Cafes                         2756
Delis                         2393
Caterers                      2059
Specialty Food                2011
Bakeries                      1889
Desserts                      1838
Japanese                      1830
Sports Bars                   1797
Sushi Bars                    1717
Barbeque                      1694
Asian Fusion                  1547
Name: categories, dtype: int64

Read the reviews JSON file (very large file, read in chunks)

In [22]:
size = 1000000
review = pd.read_json("yelp_academic_dataset_review.json",lines =True,
                      # identifying the data type of each column can reduce memory usage
                      dtype={'review_id':str,'user_id':str,'business_id':str,'stars':int,
                             'date':str,'text':str,'useful':int,'funny':int,'cool':int},
                      chunksize=size)

From the chunks merge the reviews to the businesses

In [23]:
# There are multiple chunks to be read
chunk_list = []
for chunk in review:
    # Drop columns that aren't needed
    chunk = chunk.drop(['review_id','useful','funny','cool'], axis=1)
    # Renaming column name to avoid conflict with business overall star rating
    chunk = chunk.rename(columns={'stars': 'review_stars'})
    # Inner merge with edited business file so only reviews related to the business remain
    chunk_merged = pd.merge(food, chunk, on='business_id', how='inner')
    # Show feedback on progress
    print(f"{chunk_merged.shape[0]} out of {size:,} related reviews")
    chunk_list.append(chunk_merged)
    
# After trimming down the review file, concatenate all relevant data back to one dataframe
df = pd.concat(chunk_list, ignore_index=True, join='outer', axis=0)
print(df.shape)
df.sample(3)

689501 out of 1,000,000 related reviews
677953 out of 1,000,000 related reviews
669030 out of 1,000,000 related reviews
667437 out of 1,000,000 related reviews
672860 out of 1,000,000 related reviews
690238 out of 1,000,000 related reviews
657452 out of 1,000,000 related reviews
(4724471, 18)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,user_id,review_stars,text,date
569198,6x9hcZ1CJ4S9avBgPGS7-Q,Johnny Brenda's,1201 Frankford Ave,Philadelphia,PA,19125,39.969092,-75.134266,4.0,556,1,"{'Alcohol': ''full_bar'', 'BusinessAcceptsCred...","Seafood, Greek, Food, Music Venues, American (...","{'Monday': '11:0-2:0', 'Tuesday': '11:0-2:0', ...",GvRh9s4sUpSVJYy1U5czKA,5,"If I could marry a bar, this place would be it...",2008-03-01 23:26:45
766566,Yba0u3mogMlF7QOJNVxWog,Philly Joe's Steaks & Hoagies,405 S Missouri Ave,Clearwater,FL,33756,27.961624,-82.787355,4.5,89,1,"{'OutdoorSeating': 'True', 'RestaurantsTableSe...","Soup, Cheesesteaks, Restaurants, Sandwiches","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",4EK74VqAL3Nq7VxsXZUMog,2,"I was surprised after all the good reviews, bu...",2020-08-26 00:19:28
458119,vTMDSBF1znpniWjZ02hdEw,Golden Wings,"116 Terry Pkwy, Ste C",Gretna,LA,70056,29.920893,-90.034922,4.5,71,1,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Chicken Wings, Restaurants","{'Monday': '10:0-19:0', 'Tuesday': '10:0-19:0'...",SlvlSoL-sDPTz8TFIeeszw,5,OMG!!! The best wings ever. My sister and I dr...,2014-01-07 02:33:25

Take all Edmonton resturants

In [24]:
alberta = df[df['state'] == 'AB']

In [25]:
alberta

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,user_id,review_stars,text,date
726,WKMJwqnfZKsAae75RMP6jA,Roast Coffeehouse and Wine Bar,10359 104 Street NW,Edmonton,AB,T5J 1B9,53.546045,-113.499169,4.0,40,0,"{'OutdoorSeating': 'False', 'Caters': 'True', ...","Coffee & Tea, Food, Cafes, Bars, Wine Bars, Re...","{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ...",5OnQqP3q2_9auNdDKpLdsw,3,So much to like about this place--the beautifu...,2012-11-06 23:35:15
727,WKMJwqnfZKsAae75RMP6jA,Roast Coffeehouse and Wine Bar,10359 104 Street NW,Edmonton,AB,T5J 1B9,53.546045,-113.499169,4.0,40,0,"{'OutdoorSeating': 'False', 'Caters': 'True', ...","Coffee & Tea, Food, Cafes, Bars, Wine Bars, Re...","{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ...",7qFH1RkPivVRcwxLwhyixg,4,I'm not a coffee connoisseur so I'm not review...,2013-05-28 23:16:30
728,WKMJwqnfZKsAae75RMP6jA,Roast Coffeehouse and Wine Bar,10359 104 Street NW,Edmonton,AB,T5J 1B9,53.546045,-113.499169,4.0,40,0,"{'OutdoorSeating': 'False', 'Caters': 'True', ...","Coffee & Tea, Food, Cafes, Bars, Wine Bars, Re...","{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ...",FLeyjgc05C2V6QI9nVQ48Q,4,"I really loved it here, makes me wish I lived ...",2013-09-04 19:49:33
729,WKMJwqnfZKsAae75RMP6jA,Roast Coffeehouse and Wine Bar,10359 104 Street NW,Edmonton,AB,T5J 1B9,53.546045,-113.499169,4.0,40,0,"{'OutdoorSeating': 'False', 'Caters': 'True', ...","Coffee & Tea, Food, Cafes, Bars, Wine Bars, Re...","{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ...",R-c5M0iJkMxxTxIqTQQZ8w,2,The kids who work at Roast are friendly. They...,2013-07-14 21:38:06
730,WKMJwqnfZKsAae75RMP6jA,Roast Coffeehouse and Wine Bar,10359 104 Street NW,Edmonton,AB,T5J 1B9,53.546045,-113.499169,4.0,40,0,"{'OutdoorSeating': 'False', 'Caters': 'True', ...","Coffee & Tea, Food, Cafes, Bars, Wine Bars, Re...","{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ...",G3h8pIclwUbuu3itJqF7ug,4,"With a Toast to Roast, I say welcome to the E-...",2012-09-11 23:54:24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4724466,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,2470 Guardian Road NW,Edmonton,AB,T5T 1K8,53.509649,-113.675999,4.5,18,0,"{'Ambience': '{'touristy': False, 'hipster': F...","Middle Eastern, Restaurants","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",CnzkseV3WTE5W8o5Pa7fJA,5,YES.\n\nI have been to 2 other comparable Midd...,2017-03-13 19:47:08
4724467,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,2470 Guardian Road NW,Edmonton,AB,T5T 1K8,53.509649,-113.675999,4.5,18,0,"{'Ambience': '{'touristy': False, 'hipster': F...","Middle Eastern, Restaurants","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",ZZQ0g2DnXw3iXv5LgGeY7Q,5,We had the beef plate medium rare that was mou...,2018-04-14 23:41:03
4724468,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,2470 Guardian Road NW,Edmonton,AB,T5T 1K8,53.509649,-113.675999,4.5,18,0,"{'Ambience': '{'touristy': False, 'hipster': F...","Middle Eastern, Restaurants","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",C6jwPqUk8VB0FuZO7y2MHA,5,Excellent Mediterranean food! Always cooked to...,2018-06-19 02:02:41
4724469,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,2470 Guardian Road NW,Edmonton,AB,T5T 1K8,53.509649,-113.675999,4.5,18,0,"{'Ambience': '{'touristy': False, 'hipster': F...","Middle Eastern, Restaurants","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",9b0pmwxxGIuXKXIJh__mlQ,4,This was my first visit to West Side Kebab Hou...,2017-03-24 01:46:31
4724470,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,2470 Guardian Road NW,Edmonton,AB,T5T 1K8,53.509649,-113.675999,4.5,18,0,"{'Ambience': '{'touristy': False, 'hipster': F...","Middle Eastern, Restaurants","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",eSXnEIxNm39eFgvG6TtRRg,5,Walked in on a Sunday afternoon to an empty re...,2018-02-18 22:01:43

Export to a CSV to use for future analysis notebooks

In [44]:
alberta.to_csv('albertaRestrauntReviews.csv')

In [26]:
testing = df.loc[0]

In [27]:
food_cities = df.groupby(by=['state', 'city']).aggregate({"business_id":  pd.Series.nunique, "name" : 'count'})
food_states = df.groupby(by=['state']).aggregate({"business_id":  pd.Series.nunique, "name" : 'count'})

In [28]:
food_states

       business_id     name
state
AB            2410    68882
AZ            2671   267036
CA            1161   211748
CO               1       12
DE             961    49151
FL            8731   792133
HI               1       19
ID            1302   100065
IL             983    36870
IN            4150   335843
LA            3640   558340
MO            4247   354605
MT               1        6
NC               1       29
NJ            3341   171186
NV            1673   243594
PA           12641  1100250
TN            4352   434697
XMS              1        5

In [29]:
food_cities[0:30]

                          business_id    name
state city
AB    Beaumont                      8     228
      Downtown                      1       6
      East Edmonton                 1      24
      Eaux Claires                  1      13
      EdMonton                      2      71
      Edmonton                   2166   63971
      Enoch                         1      54
      NW Edmonton                   1      10
      Saint Albert                 11     234
      Sherwood                      1      71
      Sherwood Park               136    2580
      Southeast Edmonton            1       9
      St Albert                    45     869
      St. Albert                   33     709
      West Edmonton                 2      33
AZ    Casas Adobes                  1      17
      Catalina                      7     705
      Corona De Tucson              1     204
      Corona de Tucson              1      20
      Drexel Heights                1       7
      Green Valley                 26    1468
      Marana                       39    2916
      Mount Lemmon                  4     549
      Oro Valley                   80    8971
      Picture Rocks                 1       9
      Sahuarita                    17    1016
      South Tucson                  2      39
      TUCSON                        2      61
      Tucson                     2466  249588
      Tuscon                        5     462

In [30]:
testing

business_id                                MTSW4McQd7CbVtyjqoe9mw
name                                           St Honore Pastries
address                                               935 Race St
city                                                 Philadelphia
state                                                          PA
postal_code                                                 19107
latitude                                                39.955505
longitude                                              -75.155564
stars                                                         4.0
review_count                                                   80
is_open                                                         1
attributes      {'RestaurantsDelivery': 'False', 'OutdoorSeati...
categories      Restaurants, Food, Bubble Tea, Coffee & Tea, B...
hours           {'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ...
user_id                                    6_SpY41LIHZuIaiDs5FMKA
review_stars                                                    4
text            This is nice little Chinese bakery in the hear...
date                                          2014-05-26 01:09:53
Name: 0, dtype: object

In [31]:
print(testing['text'])

This is nice little Chinese bakery in the heart of Philadelphia's Chinatown! The female cashier was very friendly (flirtatious!) and the pastries shown in nicely adorned display cases. I stopped by early one evening had a sesame ball, which was filled with bean paste. The glutinous rice of the ball was nicely flavored, similar to Bai Tang Gao. Definitely as place worth stopping at if you are in the area.

In [32]:
alberta.categories

726        Coffee & Tea, Food, Cafes, Bars, Wine Bars, Re...
727        Coffee & Tea, Food, Cafes, Bars, Wine Bars, Re...
728        Coffee & Tea, Food, Cafes, Bars, Wine Bars, Re...
729        Coffee & Tea, Food, Cafes, Bars, Wine Bars, Re...
730        Coffee & Tea, Food, Cafes, Bars, Wine Bars, Re...
                                 ...
4724466                          Middle Eastern, Restaurants
4724467                          Middle Eastern, Restaurants
4724468                          Middle Eastern, Restaurants
4724469                          Middle Eastern, Restaurants
4724470                          Middle Eastern, Restaurants
Name: categories, Length: 68882, dtype: object

In [33]:
alberta_explode = alberta.assign(categories = alberta.categories.str.split(', ')).explode('categories')

In [34]:
albertaClean = alberta[['business_id', 'name', 'address', 'stars', 'review_count', 'attributes', 'categories', 'review_stars', 'text', 'date']]

In [35]:
print('Total number of categories:', len(alberta_explode.categories.value_counts()))
print('Top 10 categories:')
print(alberta_explode.categories.value_counts()[0:10])
print("Number of restruants: ", len(alberta_explode.business_id.unique()))

Total number of categories: 274
Top 10 categories:
Restaurants               68882
Food                      18054
Nightlife                 15679
Bars                      15272
Canadian (New)            11760
Breakfast & Brunch         8407
Pizza                      6819
American (Traditional)     6503
Burgers                    6172
Italian                    6017
Name: categories, dtype: int64
Number of restruants:  2410

In [36]:
businessReview = alberta.groupby(by="name").aggregate({'text' : lambda x: (list(x)),
                                                        'review_count' : 'first'})
businessReview.sort_values(by='review_count', ascending=False)

businessReview.loc['Roast Coffeehouse and Wine Bar']['text']

["So much to like about this place--the beautiful Mercer Building location, the spaciousness, the lovely, friendly baristas. But there are a couple of important cons for me. Biggest being, the music is constant and too loud, ruining everything you go to a coffee shop to do: read, work, reflect, or enjoy a good conversation. When I asked for it to be turned down, they told me they can't--it just plays at one level all the time, and the speakers  are everywhere so you can't get away from it. It sucks.\n\nSecondly, if you're a tea drinker, you're out of luck. They don't serve the tea in pots, but huge, sloppy individual filters--it makes your beverage totally ungainly, hard to drink and is really off putting.\n\nPros: gluten free goodies and yummy Italian sodas. I'd love to spend more time here, but the music usually drives me out after 10 minutes.",
 "I'm not a coffee connoisseur so I'm not reviewing it based on that. What I am reviewing it on is the fantastic ambiance it has, the free wifi, and the long meeting table that's available for everyone.\n\nWhenever I want to hang out and work downtown at a cafe, Roast is the first place I go to. \n\nMy only real complaint is that during some hours, this place is PACKED and so that may put a kink in your plans if you wanted to meet someone there for a meeting. Also wifi is sometimes touch and go. I wish more cafes installed the fastest wifi with signal boosters around the place to make it more useful for those who telework.\n\nI also love that this place is open LATE!",
 "I really loved it here, makes me wish I lived closer and could stop by everyday! I had the dark hot chocolate & it was made in every way I like. Milky, chocolatey, whipped creamy..y? They had a maple bacon latte I could've gone for buuuut I just wasn't ready for the challenge. The atmosphere is gorgeous. Wooden floors, dark decor, BIG comfy chairs makes it cozy and warm. They also have a great looking selection of wines and some snacks as well. I think if you're planning to take a date/ co-worker/ hipster friend/ parent here is a great place to do it.\n\nOnly down side is when I went I found it VERY CROWDED. My drink ALTHOUGH WORTH IT took a good while to come about and the lemony water in the pretty dispenser was empty & I was thirsty.\n\nI do love this hipster haven.",
 "The kids who work at Roast are friendly.  They screw up things once in a blue moon, but that's to be expected.\n\nThe cookies offered there are good.  They're not the best that I've ever had, but they're good all the same.\n\nThe pain au chocolate is terrible.  It's some kind of thick, chewy abomination.  Avoid it at all costs.\n\nThe sandwiches are overpriced by about 40%.\n\nThe drinks are good enough, but they're not particularly memorable.",
 'With a Toast to Roast, I say welcome to the E-town cafe scene! I spent a few hours in this welcoming and inviting space today working & amerced in the awe inspiring ambiance. Located in the historic & newly renovated Mercer building, this coffee house by day/wine bar by night has meticulously mastered creating a spacious environment that embodies the original charm and elegance I so hoped it would have. \n\nThe pastries are fresh and delicious, the intoxicating aroma of the Roasted beans is delish, and the ode to the London Fog called the Morning Mist put a sublime smile on my face for hours after. Yes, I think I have found another regular haunt!',
 "Hope everybody had a nice Valentine's Day yesterday! I had a great dinner which lead right into our trip to San Francisco so I'll have to write about it later! In the mean time, just wanted to post up my visit to ROAST Coffeehouse on 104 St!\n\nIt took me a long time to make my way down to ROAST but I finally did it. As much as I love the atmosphere of Transcend (may you return to downtown one day) and Credo, I think I like ROAST the best! Something about the wooden interior, the expansive seating areas and trendy wallpaper makes it a place where I'd want to sit and relax.\n\nJoe and I went on a Sunday afternoon and the place was pretty bustling from what would have expected. Another plus: their menu is extensive, serving up specialty drinks as well (Credo, please expand, I can't drink straight coffee!). ROAST also serves food and wine after 4pm, which makes me want to return ASAP!\n\nFor that day though, we were happy with our drinks. Joe and his regular latte, decorated with their signature 'R' (to go, because he just had a cup of coffee with breakfast), and a dark chocolate mocha for me. This is the first time I've ever had a mocha where I didn't find was too bitter (aside from anything served at Starbucks, pure cream and sugar). Absolutely loved my drink!\n\nROAST Coffeehouse, thus far, is my favorite out of all coffee hangouts. Runner-up: Wild Earth Bakery. I only wished I discovered these places when I was in school! Perfect place to study. What's your favorite coffee place?",
 "I've only been once, but think Roast is worth plenty more trips in the future.\n\nThe take on a London Fog I had was pretty tasty. I like a little more sweetness but, then, a little less sugar is a healthy thing.\n\nThe place looks fantastic! As part of the re-birth of the Mercer Warehouse, Roast has all the exposed brick, wood, and everything else so often behind walls that anyone could ask for. A very cool space on Edmonton's new cool street. Let me know if you sit at their community table.",
 "I love Roast, it's my place to escape during a crazy day at the office. Yes, it's quite hipster but I still love it. The brick walls, the pressed tin ceiling, the local artwork and the reclaimed wood tables -- and of course the coffee. I was disappointed when they took their maple bacon latte off the menu, I think that drew in a lot of people here. But they said it cost too much to keep on the menu, unfortunately.\n\nI still enjoy the chocolate cherry latte, it's not as sweet as it sounds. The pumpkin pie latte is also good, and I hear the chai hot chocolate is a treat too. The toasted marshmallow latte is quite sweet though, just to warn you. For a cold option, I like the coconut frap .. it's nice and light, not too sweet. You can switch between cold and hot for most of these options though.\n\nI've always found their pastries to be delicious and never stale, unlike other coffee houses. The lemon swirl is to die for, if you like a strong lemon taste -- lots of flavour in every bite, with chunks of chewy lemon. Yum! The cinnamon swirl and chocolate croissants are also tasty. I was sad when they discontinued their key lime cookie, those were delicious! Unfortunately it wasn't popular enough so they took that off the menu too.\n\nGo earlier in the day if you want to score a pastry with your coffee, otherwise it's usually just sandwiches left by the afternoon and I'm not so sure about those if they've been left out since morning.",
 "Great meeting place in the mornings.  Lots of available parking and a great atmosphere.  The latte was really good and Roast has several different flavours that I can't normally find in the chain brands.\n\nService was really good and the drink was made quickly.  Wish they had a paper to read or Avenue magazine but there wasn't anything readily available, but that isn't a huge deal.\n\nSeating is really comfortable and is far better than the mostly wooden chairs you find at large chain coffee shops.  I'll be back again and again.",
 "Roast where have you been all my life! How do I love thee, let me count the ways!  1. Being surrounded by what seems like the most comfortable coffee shop seating in the city. 2. Nice exposed brick of a past era. 3. Reclaimed old wood flooring. 4. Down to earth extremely friendly staff. 5. A good mix of the business, student and everyone else crowd. 6. Cozy gas fireplaces. 7. An all around cool atmosphere. All these factors have a way of making 2 or 3 hours fly by. \n\nI got med coffee ($3) and a MAPLE BACON cinnamon bun ($3.75). Nothing here is cheap and admittedly the coffee isn't the best in the city. But I really love the atmophere.\n\nMy only complaints would be that the music can be a little too loud and that some of the tables are wobbly. However, this is one of my favourite places to meet someone for coffee.\n\nI absolutely, positively, most definitely, unequivocally, with out a doubt, love Roast!",
 "Roast has been around for a little while now, and do indeed have excellent coffee. The café is moderately sized and fairly open, but it makes up for the open space by creating comfortable nooks and separate seating areas throughout the room. There are couches towards the street-side, booths and high tables near the middle, and high-backed chairs and coffee tables located in the direction of the rear.\n\nIt isn't just the coffee or the rustic atmosphere that makes Roast so fantastic, though. They've recently undergone a menu overhaul and, rather than just the usual cakes, pastries, and sweets, now offer breakfast and lunch options à la Chef Andrew Parker, which change daily.\n\nAnd, yeah...they sell wine. It's always a tough decision for me once I reach the counter at Roast, since I love coffee and I adore wine. Roast's wine selection is fabulous because it serves up a variety of reds, whites, and rosés from across Canada, keeping it local and supporting wineries from the Okanagan and Niagara regions.\n\nThe café is also a great location for holding events (particularly literary/artsy ones) or hosting a meeting (they have a Community Room to accommodate them).\n\nDid I mention that they serve a Maple Bacon Latte? (I knew that would sell you on it.)",
 "Delicious coffee, great service, wonderful atmosphere.\nBest soy vanilla latte in town. I don't care how much it costs, it's the best.  But don't you worry, the prices are similar to those of other coffee joints in Edmonton.",
 "A great trendy coffee house on my favourite street in the city. Roast is great for a couple reasons 1) they have amazing lattes, the salted caramel is definitely something to be sought after 2) the prices aren't much higher than that of Starbucks. \n\nThe boyfriend and I adore coffee in a can't-function-without-it-in-the-morning kind of a way. We are always on the lookout for great coffee places and Roast definitely falls into that category! \n\nWe were both pleasantly surprised to find a maple bacon latte on the menu and of course the boyfriend had to try it. I was also happy to see wine (and Canadian wine at that) on their menu. Canadian wines are typically some of the best wines around! \n\nRoast also introduced me to a great new rewards program, Perka! I was happy to learn that after 6 coffees you receive a free drink! This rewards program trumps any Starbucks gold star reward program. \n\nI will definitely be back to this great little coffee house!",
 "I really love Roast, though I find it expensive. They serve your standard coffee drinks, with some twists like a bacon & maple latte. I love the option of ordering a beer or wine when I meet my friend for coffee, because sometimes, at the end of a work day, that's just what you need. They don't have a bad collection either, and I'm impressed with the unique variety of import bottles. Roast is a nice venue too, with exposed beams and brick, and they frequently have live music. There's few things more wonderful than curling up in an armchair in front of a fire with a good drink, and listen to someone strum a guitar. Roast is a regular stop on my favorite coffeeshop rotation, and I'll keep coming back for more.",
 'By far, my favourite coffeehouse in the city! I have never had great coffee until I started going to Roast. \n\nWe stop in at least once a week, more if I have the time. I usually have the pleasure of seeing Josh in the mornings, and he is just so friendly (as is all the staff there) and I am pretty sure he remembered my name after the first time I came to Roast.\n\nThe drinks are all fabulous, and the small amount of food I have tried here, I have enjoyed. \n\nOh if you remember to, order one of their cookies! They are delicious and I am sad I only discovered them almost a year after they opened.',
 "I was surprised to hear that this place had closed. Too cool for Edmonton. It's also a difficult balance for a cafe between making a place feel cosy enough to spend hours there, and having people actually buy 1 drink and spending hours there.",
 "The decor is fantastic and the staff are friendly. The coffee profile is a little dark for my liking, and the music is 50% terrible, but the atmosphere is otherwise a joy. I've enjoyed some nice events there as well.",
 "No Wheelchair Access!\n\n- How is it that they just did a giant renovation, and somehow managed to get by the requirement to install a ramp and wheelchair accessible washrooms?\n\nIf you would like to try this coffee house, you'd better not be in a wheelchair.",
 'I went there yesterday afternoon for the first time ever, and I feel like an idiot for not going there everyday since they opened.\n\nVery lovely and cozy atmosphere, great for coffee and chat with friends, and for working or studying.\n\nTheir coffee is simply fantastic, the baristas are incredible at what they do. Highly recommended!',
 'I really enjoy going to Roast to work during the day. They have amazing customer service, their espresso is pretty good, and the ambience is perfect for an afternoon of working. I would recommend their vanilla iced lattes. \n\nThe only thing I would say is make sure you get a spot by a charger, as there are only a few of them. Also use their loyalty program!',
 "I'm always finding new ways to get in the way of a regular sleeping schedule so it doesn't surprise me that most of the time I head to Roast, I'm scooted out not long after because they're closing.\n\nThe atmosphere is part local and rustic feeling and the other part is a Jay Z and Kanye West collaborative album cover. Flash, shine, and wood. The tank of water for all customers is a nice touch especially when they chop some cucumber in there.\n\nThe coffee and tea menu is pretty plain and basic but the baristas know what they're doing and made sure I got my custom Gibraltar (3 parts espresso, 2 parts steamed milk) the way I want it. The most pleasant surprise was the wine and beer selection, I usually spy into the beer fridge and am forced make a difficult decision with a kind of beer or even getting one at all.\n\nRoast is a great place whether you're there to relax or have an awkward first date.",
 "As several other reviewers have observed, this place looks very good. One wants to like it. The management, however, is so clueless that I have decided to permanently give it a pass. There are so many really good places in this area where the management knows how to retain good people that one need not spend time in a place where the servers seem to change on a daily basis.\n\nWhen I buy high-priced coffee, I like to have it in a real mug, not a cardboard cup that I could get at any fast-food joint. When the people here mistakenly put mine in a cardboard cup, I did not ask for a new coffee. Instead, I politely pointed it out in the hopes that they would get it right the next time. In return, I got an argument and nasty looks from the crew at the counter. Also, no matter now many people they have at the counter, they manage to keep even small groups of customers waiting on long lines.\n\nYesterday was the kicker. I asked for a decaf coffee and told there was no decaf. Even your average diner will usually ask a customer if he or she wants to wait while they brew up a pot of decaf. And this is a fancy café? I then asked if they had decaf espresso and was told that this too was all out. The person telling me this clearly had no idea of her surroundings and thought she was working in some civil service office: nope, we ain't got it, too bad!\n\nWith so many good options down the block, this place should stop relying on their decor.",
 'just came by here today, great design and warm atmosphere. had the chocolate cherry frappucino. will definitely be back',
 "Roast Coffeehouse has a lot going for it.  The ambience is lovely, located in the high-ceilinged Mercer building in the warehouse district.  Charming interiors, quite beautiful furniture, intriguing wall art, Edison-era light installations and what not.  They might have the best ambience any cafe in Edmonton has.  Perfect date place too, I think, with decent music playing and comfortable furniture for quiet conversations.\n\nI've been here twice and agree with most reviewers in that they make interesting latte creations and teas.   I think they briefly had a caramel-bacon latte which sounds really interesting and I enjoyed their salted caramel latte.  They have a collection of craft beers and wines mainly from AB and the Okanagan region.  It's interesting and I'm glad they support local craft brews and wines, though at least on the beer front, these regions are not known for the best craft brews in Canada.\n\nWhy the 3 stars? Many might consider me a coffee snob when I say this, but I actually think that for $5, it's only fair that the quality of the actual espresso be far better than something you would get at a chain coffee shop.  This, however, they lack in.  The staff seem to know very little about actual coffee and how to make a good espresso and this disappoints me a little.  It's got a bit of a yuppie feel to it without delivering a quality product.  \n\nI am not sure if I will go back because I know of places that make better coffee. There are many in Edmonton now (Elm, Transcend, Leva, Credo, Sugar Bowl, da Capo etc.) and to open up a new coffee shop and not strive to at least equal the bar set by these establishments, especially when they charge as much (some cases, more) as these other well established coffee joints, is a little disappointing for me.\n\nCome here for an interesting flavored latte, but don't come if you demand high quality coffee.  The main reason for three stars is that they claim to be a coffeehouse first and don't do too well, in my books, on that front.",
 "Roast is new to the coffee house scene in Edmonton, but they are some serious competition. Set in the delightfully trendy Mercer Building alongside Mercer Tavern, Startup Edmonton and FaBLOOMosity ( a flower shop), Roast's second floor decor is comfy luxury. \n\nThey are having some just-opened growing pains that involves installing a new transformer to handle the expresso machine but they are still open for business offering delectable breakfast and lunch options, brewed Verve coffee and some soul-changing loose leaf iced teas. \n\nAfter Friday's Social Media Breakfast at Startup Edmonton, a few of us work-tardy folks went down to sample Roast. \n\nGreeted right away by happy people, they won me over by spelling my name on my cup correctly without any prompts. Oh they know the way to a girl's heart. \n\nMy iced tea was a blend of sun-kissed fields, summer promises and a splash of warm rain and my friend's no-caffeine Italian soda option was made with hugs & kisses. \n\nOpening at 6 am means they are dedicated to the early morning downtown set. Actually their evening hours mean that downtown just got more accessible.\n\nMonday - 6:00am to 10:00pm\nTuesday - 6:00am to 10:00pm\nWednesday - 6:00am to 10:00pm\nThursday - 6:00am to 10:00pm\nFriday - 6:00am to 11:00pm\nSaturday - 7:00am to 11:00pm\nSunday - 8:00am to 9:00pm\n\nFollow them on Facebook/Twitter for tea & menu options as well as any specials they have each day.",